### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by stereodruid** [stereodruid/plugin.video.pseudo.library#3]
Update Status hängt bei  0%

**Comment by breaksrmine** [comment]
mit manuell meine ich , das manuelle Aktualisieren der Bib

settings2.xml kann ich weder im besagten, noch in anderen Ordnern finden.
Wie bereits gesagt, es handelt sich um eine komplette Neuinstallation (Kodi + PL)

**Comment by stereodruid** [comment]
Das ist sehr eigenartig, in der Settings2 werden die Links zu den Serien und Filmen gespeichert, sowie der Name und der Typ.
Wenn du also eine Serie hinzugefügt hast, muss es die Datei geben. In den Einstellungen von PL, kannst du den Speicherort, in dem die strms gespeichert werden, bestimmen. Im selben Ordner sollte auch die Settings2 liegen.

**Comment by stereodruid** [comment]
Wenn du keine Serien oder Musik hinzugefügt hast, dann  wird es wohl ein Fehler sein. Warscheinlich versucht PL ein Update von Nichts zu machen. Das kann ich anpassen. Oder das Autoupdate standardmäßig auf deaktiviert setzen.

**Comment by breaksrmine** [comment]
Ich habe 5-6 Serien hinzugefügt. Schaue nachher nochmal zu Hause und melde mich dann

**Comment by breaksrmine** [comment]
![102916152308](https://cloud.githubusercontent.com/assets/18583562/19829836/c7eda006-9deb-11e6-94f2-592973c7ad3c.png)
![102916152342](https://cloud.githubusercontent.com/assets/18583562/19829837/ccadb5d6-9deb-11e6-8e0a-22f1dcb46e35.png)

**Comment by stereodruid** [comment]
Hab einen Fehler gefunden der für das Problem verantwortlich sein könnte. Werde morgen einen Update machen.

**Comment by breaksrmine** [comment]
Ok, super. 

PS das automatische Update scheint bei mir nicht zu funktionieren. Weder bei TWD, noch agents of shield kam eine neue Folge dazu (beides SeriesEver)

**Comment by stereodruid** [comment]
Ich habe den Fehler gestern behoben. Problem war das schreiben in die Settings2.xml.
Die Einträge muüssen wie folgt aussehen:
TV-Show|Serienname|URL
TV-Show|Serienname|URL
TV-Show|Serienname|URL

Bitte prüfe ob deine Einträge alle untereinander eingetragen sind, also ein Eintrag pro Zeile.

Durch den Fehler wurden manche Einträge hintereinander geschrieben. Das kannst du manuell korrigieren, dann sollte alles funktionieren.

**Comment by breaksrmine** [comment]
ich habe auch nach dem update immer noch garkeine settings2.xml im Ordner userdata/pseusolibrary/

**Comment by stereodruid** [comment]
Userdata\app_data\...?

**Comment by breaksrmine** [comment]
Da isse:) schau ich mir morgen mal an

**Comment by stereodruid** [comment]
Wäre doch gelacht wenn wir das nicht schaffen;)

**Comment by breaksrmine** [comment]
so, alle Serien gelöscht und neu geladen, damit sie nun auch in der settings2.xml landen. Scheint alles gut zu klappen. Jetzt bin ich auf die erste neue Folge gespannt :)

PS Mir scheint, als würde PL bei der Aktualisierung sämtliche Staffeln durchgehen, evtl. kann man dies auf die Staffel mit der höchsten Nummerierung begrenzen, da in den alten Staffeln sowieso nichts Neues kommt...?

**Comment by stereodruid** [comment]
Super, ich hoffe das jetzt alles funktioniert. Ich wer de mir mal anschauen wie man das umsetzen könnte. Allerdings werden, nach einiger Zeit, die Folgen aus den alten staffeln nicht mehr funktionieren, da die Links veralten.

**Comment by breaksrmine** [comment]
Stimmt wohl. Mir wäre das prinzipiell egal, da für mich der einzige Grund eine ganze Serie, anstelle einer einzigen Staffel in die Library zu packen, der ist, dass auch Folgestaffeln automatisch erfasst werden sollen. 
Vll dann eher eine optionale Sache
