### ISSUE TITLE
Update coming soon...

### ISSUE THREAD

**Issue by Lunatixz** [stereodruid/plugin.video.pseudo.library#4]
@stereodruid wanted to check in let you know i'm still working on various projects. One of them updating pseudoLibrary... before I push a update... was there anything else that needed to be fixed?

**Comment by stereodruid** [comment]
Hey @Lunatixz, no there's nothin else to be fixed.
I just added some new functions like a dialogue that displays a list of added content. In this dialogue you can delet items from settings2 by selecting them in a list. Also the section music addon is working now and PL can write a nfo file for each title now.

**Comment by Lunatixz** [comment]
Hey i'm confused... I thought we were working together on one project... I see you've created another support page for your fork?? 
http://www.kodinerds.net/index.php/Thread/53307-Beta-Version-PseudoLibrary-Streams-zur-DB-hinzuf%C3%BCgen/

This is the proper support page:
http://forum.kodi.tv/showthread.php?tid=245318

I thought we agreed to work together? I've been in the process of properly rewriting this plugin from the ground up... but if you feel this project is in better hands with you... I've got better things to do.

I'll suspend my work on this plugin... I solely started this project again because you admitted you were not a coder and I wanted to help you. I absolutely don't understand why you would need to fork the old code and open another forum using the same script ids as mine... this isn't proper...

Good luck with your project...
